pipeline:
  name: wifr-sensitivity-second
description: "Create wifr simulation from input random seeds"
standby: true
transform:
  image: k8scc01covidacr.azurecr.io/kenchu-wifr-nogit:v3
  image_pull_secrets:
    - k8scc01covidacr-registry-connection
  cmd:
    - "/main.sh"
    - "--src"
    - "/src/"
    - "--params"
    - "/pfs/params/"
    - "--data"
    - "/pfs/data/"
    - "--output"
    - "/pfs/out"
    - "--nproc"
    - "2"
resource_requests:
  memory: "2G"
  cpu: 2
resource_limits:
  memory: "3G"
  cpu: 3
parallelism_spec:
  constant: 100  # use N pods
output_branch: 2020-04-26_01
input:
  cross:
    - pfs:
        name: params
        repo: wifr-params
        glob: "/*/*"
    - pfs:
        name: data
        repo: wifr-data
        glob: "/"
        branch: 2020-04-26_01
